import fs from 'fs';
const lines = [];
function add(s) { lines.push(s); }

add('"use client"');
add('');
add('import * as React from "react"');
add('import { motion } from "framer-motion"');
add('import { ScrollReveal, HeroParallax } from "@/components/motion"');
add('import { Container, SectionWrapper } from "@/components/layout"');
add('import { cn } from "@/lib/utils"');
add('import { useMobileOptimization } from "@/hooks/use-mobile-optimization"');
add('import {');
add('  SiC, SiCplusplus, SiOpenjdk, SiJavascript, SiPython,');
add('  SiReact, SiHtml5, SiCss, SiNodedotjs, SiTensorflow,');
add('  SiOpencv, SiPandas, SiScikitlearn, SiMongodb, SiMysql,');
add('  SiSqlite, SiSupabase, SiChartdotjs, SiFirebase, SiDjango,');
add('  SiBootstrap, SiGit,');
add('} from "react-icons/si"');
add('');
add('const SKILL_ICON_MAP = {');
add('  C: SiC,');
add('  "C++": SiCplusplus,');
add('  Java: SiOpenjdk,');
add('  JavaScript: SiJavascript,');
add('  Python: SiPython,');
add('  React: SiReact,');
add('  HTML5: SiHtml5,');
add('  CSS3: SiCss,');
add('  "Node.js": SiNodedotjs,');
add('  TensorFlow: SiTensorflow,');
add('  OpenCV: SiOpencv,');
add('  Pandas: SiPandas,');
add('  "Scikit-learn": SiScikitlearn,');
add('  MongoDB: SiMongodb,');
add('  MySQL: SiMysql,');
add('  SQLite: SiSqlite,');
add('  Supabase: SiSupabase,');
add('  "Chart.js": SiChartdotjs,');
add('  Firebase: SiFirebase,');
add('  Django: SiDjango,');
add('  Bootstrap: SiBootstrap,');
add('  Git: SiGit,');
add('}');
add('');
add('const skillsCategories = [');
add('  { title: "Programming Languages", icon: "\\\\u{1F4BB}", color: "cyber-blue", skills: ["C","C++","Java","JavaScript","Python"], description: "Core programming foundations" },');
add('  { title: "Frontend Development", icon: "\\\\u{1F3A8}", color: "cyber-purple", skills: ["React","HTML5","CSS3"], description: "Modern web interface development" },');
add('  { title: "Backend Development", icon: "\\\\u{2699}\\\\u{FE0F}", color: "cyber-blue", skills: ["Node.js"], description: "Server-side architecture" },');
add('  { title: "AI / ML", icon: "\\\\u{1F916}", color: "cyber-purple", skills: ["TensorFlow","OpenCV","Pandas","Scikit-learn"], description: "Machine learning and AI systems" },');
add('  { title: "Database", icon: "\\\\u{1F5C4}\\\\u{FE0F}", color: "cyber-blue", skills: ["MongoDB","MySQL","SQLite","SQL Server","Supabase"], description: "Data storage and management" },');
add('  { title: "Data Visualization", icon: "\\\\u{1F4CA}", color: "cyber-purple", skills: ["Chart.js"], description: "Visual data representation" },');
add('  { title: "Backend as a Service", icon: "\\\\u{1F527}", color: "cyber-blue", skills: ["Firebase"], description: "Cloud backend services" },');
add('  { title: "Framework", icon: "\\\\u{1F3D7}\\\\u{FE0F}", color: "cyber-purple", skills: ["Django","Bootstrap"], description: "Development frameworks" },');
add('  { title: "Version Control", icon: "\\\\u{1F501}", color: "cyber-blue", skills: ["Git"], description: "Code version management" },');
add(']');
add('');
add('const FloatingSkillIcon = React.forwardRef(({ skill, index, categoryIndex, delay, color }, ref) => {');
add('  const [isHovered, setIsHovered] = React.useState(false)');
add('  const [floatValues, setFloatValues] = React.useState({ x: 0, y: 0, rotateY: 0 })');
add('  const IconComponent = SKILL_ICON_MAP[skill]');
add('  React.useEffect(() => {');
add('    const animateFloat = () => {');
add('      const time = Date.now() * 0.001');
add('      const x = Math.sin(time * 0.5 + categoryIndex * 0.8 + index * 0.3) * 8');
add('      const y = Math.cos(time * 0.3 + categoryIndex * 0.6 + index * 0.2) * 6');
add('      const rotateY = Math.sin(time * 0.4 + index * 0.5) * 15');
add('      setFloatValues({ x, y, rotateY })');
add('    }');
add('    const interval = setInterval(animateFloat, 50)');
add('    return () => clearInterval(interval)');
add('  }, [categoryIndex, index])');
add('  const colorBlue = color === "cyber-blue"');
add('  const borderClass = colorBlue ? "border-cyber-blue/30 hover:border-cyber-blue/80 hover:shadow-cyber-blue/40" : "border-cyber-purple/30 hover:border-cyber-purple/80 hover:shadow-cyber-purple/40"');
add('  const iconBgClass = colorBlue ? "bg-linear-to-br from-cyber-blue/30 to-cyber-blue/10 text-cyber-blue border border-cyber-blue/30" : "bg-linear-to-br from-cyber-purple/30 to-cyber-purple/10 text-cyber-purple border border-cyber-purple/30"');
add('  const dotColor = colorBlue ? "#3b82f6" : "#a855f7"');
add('  const lineGradient = colorBlue ? "linear-gradient(to right, transparent, #3b82f6, transparent)" : "linear-gradient(to right, transparent, #a855f7, transparent)"');
add('  const glowClass = colorBlue ? "bg-linear-to-r from-cyber-blue/30 via-cyber-blue/20 to-cyber-purple/20" : "bg-linear-to-r from-cyber-purple/30 via-cyber-purple/20 to-cyber-blue/20"');
add('  return (');
add('    <motion.div');
add('      ref={ref}');
add('      initial={{ opacity: 0, scale: 0.6, rotateY: -45, y: 30 }}');
add('      whileInView={{ opacity: 1, scale: 1, rotateY: 0, y: 0 }}');
add('      transition={{ duration: 0.8, delay: delay + (index * 0.1), ease: [0.25, 0.1, 0.25, 1] }}');
add('      onHoverStart={() => setIsHovered(true)}');
add('      onHoverEnd={() => setIsHovered(false)}');
add('      style={{');
add('        transform: "perspective(1000px) rotateY(" + floatValues.rotateY + "deg) translate3d(" + floatValues.x + "px, " + floatValues.y + "px, 0)",');
add('        transformStyle: "preserve-3d",');
add('      }}');
add('      className={cn("relative group cursor-pointer px-2.5 py-2 rounded-lg border bg-linear-to-br from-background/70 to-background/40 backdrop-blur-md transition-all duration-700 ease-out hover:scale-110 hover:z-20", borderClass)}');
add('    >');
add('      <motion.div');
add('        className={cn("absolute -inset-2 rounded-lg opacity-0 transition-opacity duration-700", glowClass)}');
add('        animate={{ opacity: isHovered ? 1 : 0, scale: isHovered ? [1, 1.3, 1] : 1, rotate: isHovered ? [0, 180, 360] : 0 }}');
add('        transition={{ duration: 3, repeat: isHovered ? Infinity : 0, ease: "easeInOut" }}');
add('      />');
add('      <div className="relative z-10 flex items-center space-x-2">');
add('        <motion.div');
add('          className={cn("w-7 h-7 rounded-md flex items-center justify-center text-xs font-bold shadow-lg", iconBgClass)}');
add('          animate={{ rotateX: isHovered ? [0, 360] : 0, rotateY: isHovered ? [0, 180] : 0, scale: isHovered ? 1.3 : 1, y: isHovered ? -4 : 0, z: isHovered ? 50 : 0 }}');
add('          transition={{ duration: 0.8, ease: [0.25, 0.1, 0.25, 1] }}');
add('          style={{ transformStyle: "preserve-3d" }}');
add('        >');
add('          {IconComponent ? <IconComponent className="w-4 h-4 drop-shadow-lg" /> : <span className="drop-shadow-lg">{skill.charAt(0)}</span>}');
add('        </motion.div>');
add('        <motion.div');
add('          className="space-y-0.5"');
add('          animate={{ x: isHovered ? 3 : 0, opacity: isHovered ? 1 : 0.9, scale: isHovered ? 1.05 : 1 }}');
add('          transition={{ duration: 0.4 }}');
add('        >');
add('          <motion.span className="text-xs font-bold text-foreground block" animate={{ letterSpacing: isHovered ? "0.05em" : "normal" }} transition={{ duration: 0.3 }}>');
add('            {skill}');
add('          </motion.span>');
add('          <motion.div');
add('            className="h-0.5 bg-linear-to-r from-transparent via-current to-transparent opacity-0"');
add('            animate={{ width: isHovered ? "100%" : "0%", opacity: isHovered ? 0.6 : 0 }}');
add('            transition={{ duration: 0.4 }}');
add('            style={{ background: lineGradient }}');
add('          />');
add('        </motion.div>');
add('      </div>');
add('      <motion.div');
add('        className="absolute -bottom-10 left-1/2 transform -translate-x-1/2 px-3 py-1.5 rounded-lg bg-background/95 backdrop-blur-md border border-border/50 shadow-xl z-30 whitespace-nowrap"');
add('        initial={{ opacity: 0, y: 10, scale: 0.8 }}');
add('        animate={{ opacity: isHovered ? 1 : 0, y: isHovered ? 0 : 10, scale: isHovered ? 1 : 0.8 }}');
add('        transition={{ duration: 0.4, ease: [0.25, 0.1, 0.25, 1] }}');
add('      >');
add('        <div className="text-center space-y-0.5">');
add('          <p className="text-[10px] font-medium text-foreground">Expert Level</p>');
add('          <div className="flex items-center space-x-0.5 justify-center">');
add('            {[...Array(5)].map((_, i) => (');
add('              <motion.div');
add('                key={i}');
add('                className="w-1 h-1 rounded-full"');
add('                style={{ background: dotColor }}');
add('                animate={{ scale: isHovered ? [1, 1.2, 1] : 1, opacity: i < 4 ? 1 : 0.3 }}');
add('                transition={{ duration: 0.5, delay: i * 0.1 }}');
add('              />');
add('            ))}');
add('          </div>');
add('        </div>');
add('      </motion.div>');
add('      {isHovered && (');
add('        <div className="absolute inset-0 overflow-hidden rounded-lg">');
add('          {[...Array(6)].map((_, i) => (');
add('            <motion.div');
add('              key={i}');
add('              className={cn("absolute w-0.5 h-0.5 rounded-full", colorBlue ? "bg-cyber-blue" : "bg-cyber-purple")}');
add('              style={{ top: Math.random() * 100 + "%", left: Math.random() * 100 + "%" }}');
add('              animate={{ y: [0, -20, 0], x: [0, Math.random() * 10 - 5, 0], opacity: [0, 1, 0], scale: [0, 1, 0] }}');
add('              transition={{ duration: 2 + Math.random(), repeat: Infinity, delay: Math.random() * 0.5, ease: "easeInOut" }}');
add('            />');
add('          ))}');
add('        </div>');
add('      )}');
add('    </motion.div>');
add('  )');
add('})');
add('FloatingSkillIcon.displayName = "FloatingSkillIcon"');
add('');
add('const SkillCategoryModule = React.forwardRef(({ category, index }, ref) => {');
add('  const [isHovered, setIsHovered] = React.useState(false)');
add('  const colorBlue = category.color === "cyber-blue"');
add('  return (');
add('    <motion.div');
add('      ref={ref}');
add('      initial={{ opacity: 0, y: 50 }}');
add('      whileInView={{ opacity: 1, y: 0 }}');
add('      transition={{ duration: 0.8, delay: index * 0.15, ease: [0.25, 0.1, 0.25, 1] }}');
add('      onHoverStart={() => setIsHovered(true)}');
add('      onHoverEnd={() => setIsHovered(false)}');
add('      className={cn( "relative group cursor-pointer p-5 rounded-2xl border bg-linear-to-br from-background/60 to-background/30 backdrop-blur-xl transition-all duration-700 ease-out hover:scale-[1.02] hover:border-opacity-50", colorBlue ? "border-cyber-blue/20 hover:border-cyber-blue/40 hover:shadow-cyber-blue/20" : "border-cyber-purple/20 hover:border-cyber-purple/40 hover:shadow-cyber-purple/20")}');
add('    >');
add('      <motion.div');
add('        className={cn("absolute inset-0 rounded-2xl opacity-0 transition-opacity duration-700", colorBlue ? "bg-linear-to-br from-cyber-blue/10 via-transparent to-cyber-purple/5" : "bg-linear-to-br from-cyber-purple/10 via-transparent to-cyber-blue/5")}');
add('        animate={{ opacity: isHovered ? 1 : 0 }}');
add('      />');
add('      <motion.div className="absolute inset-0 overflow-hidden rounded-2xl">');
add('        {[...Array(3)].map((_, i) => (');
add('          <motion.div');
add('            key={i}');
add('            className={cn("absolute w-1 h-1 rounded-full", colorBlue ? "bg-cyber-blue/40" : "bg-cyber-purple/40")}');
add('            style={{ top: (20 + i * 30) + "%", left: (10 + i * 25) + "%" }}');
add('            animate={{ y: isHovered ? [0, -10, 0] : [0, 0, 0], opacity: isHovered ? [0.4, 1, 0.4] : [0.2, 0.2, 0.2] }}');
add('            transition={{ duration: 2 + i * 0.5, repeat: isHovered ? Infinity : 0, ease: "easeInOut", delay: i * 0.2 }}');
add('          />');
add('        ))}');
add('      </motion.div>');
add('      <div className="relative z-10 space-y-4">');
add('        <div className="flex items-center justify-between">');
add('          <div className="flex items-center space-x-2">');
add('            <motion.div');
add('              className={cn("w-9 h-9 rounded-xl flex items-center justify-center text-xl", colorBlue ? "bg-cyber-blue/20 text-cyber-blue" : "bg-cyber-purple/20 text-cyber-purple")}');
add('              animate={{ rotate: isHovered ? [0, 5, -5, 0] : 0, scale: isHovered ? 1.1 : 1 }}');
add('              transition={{ duration: 0.6 }}');
add('            >');
add('              {category.icon}');
add('            </motion.div>');
add('            <div>');
add('              <motion.h3 className="text-base font-bold text-foreground" animate={{ x: isHovered ? 2 : 0 }} transition={{ duration: 0.3 }}>');
add('                {category.title}');
add('              </motion.h3>');
add('              <motion.p className="text-xs text-muted-foreground" animate={{ opacity: isHovered ? 1 : 0.7 }} transition={{ duration: 0.3 }}>');
add('                {category.description}');
add('              </motion.p>');
add('            </div>');
add('          </div>');
add('          <motion.div');
add('            className="text-xs text-muted-foreground/70"');
add('            animate={{ rotate: isHovered ? 90 : 0, opacity: isHovered ? 1 : 0.5 }}');
add('            transition={{ duration: 0.4 }}');
add('          >');
add('            &rarr;');
add('          </motion.div>');
add('        </div>');
add('        <div className="grid grid-cols-2 md:grid-cols-3 gap-2">');
add('          {category.skills.map((skill, skillIndex) => (');
add('            <FloatingSkillIcon');
add('              key={skill}');
add('              skill={skill}');
add('              index={skillIndex}');
add('              categoryIndex={index}');
add('              delay={0.3 + (index * 0.1)}');
add('              color={category.color}');
add('            />');
add('          ))}');
add('        </div>');
add('        <motion.div');
add('          className="text-center text-xs text-muted-foreground/60 italic"');
add('          initial={{ opacity: 0, height: 0 }}');
add('          animate={{ opacity: isHovered ? 1 : 0, height: isHovered ? "auto" : 0 }}');
add('          transition={{ duration: 0.4, ease: [0.25, 0.1, 0.25, 1] }}');
add('        >');
add('          {category.skills.length} technologies mastered');
add('        </motion.div>');
add('      </div>');
add('    </motion.div>');
add('  )');
add('})');
add('SkillCategoryModule.displayName = "SkillCategoryModule"');
add('');
add('const SkillsSection = React.forwardRef(({ className, ...props }, ref) => {');
add('  return (');
add('    <SectionWrapper');
add('      ref={ref}');
add('      id="skills"');
add('      background="cinematic"');
add('      padding="xl"');
add('      className={cn("relative overflow-hidden", className)}');
add('      {...props}');
add('    >');
add('      <HeroParallax speed={0.3} className="absolute inset-0">');
add('        <div className="absolute top-10 left-20 w-40 h-40 bg-cyber-blue/8 rounded-full blur-3xl" />');
add('        <div className="absolute bottom-10 right-20 w-48 h-48 bg-cyber-purple/8 rounded-full blur-3xl" />');
add('        <div className="absolute top-1/3 left-1/4 w-32 h-32 bg-cyber-blue/5 rounded-full blur-2xl" />');
add('        <div className="absolute bottom-1/3 right-1/4 w-36 h-36 bg-cyber-purple/5 rounded-full blur-2xl" />');
add('      </HeroParallax>');
add('      <Container size="cinematic" className="relative z-10">');
add('        <div className="max-w-6xl mx-auto space-y-16">');
add('          <motion.div');
add('            initial={{ opacity: 0, y: 40 }}');
add('            whileInView={{ opacity: 1, y: 0 }}');
add('            transition={{ duration: 1.2, ease: [0.25, 0.1, 0.25, 1] }}');
add('            className="text-center space-y-8"');
add('          >');
add('            <motion.h2');
add('              className="text-5xl md:text-7xl font-black tracking-tight"');
add('              initial={{ scale: 0.9 }}');
add('              whileInView={{ scale: 1 }}');
add('              transition={{ duration: 0.8, delay: 0.2 }}');
add('            >');
add('              <span className="bg-linear-to-r from-cyber-blue via-cyber-purple to-cyber-blue bg-clip-text text-transparent bg-size-[200%_auto] animate-gradient">');
add('                CAPABILITIES');
add('              </span>');
add('            </motion.h2>');
add('            <motion.div');
add('              className="w-32 h-1 mx-auto bg-linear-to-r from-cyber-blue to-cyber-purple rounded-full"');
add('              initial={{ width: 0 }}');
add('              whileInView={{ width: 128 }}');
add('              transition={{ duration: 1, delay: 0.4 }}');
add('            />');
add('            <motion.p');
add('              className="text-xl text-muted-foreground leading-relaxed font-light max-w-3xl mx-auto"');
add('              initial={{ opacity: 0 }}');
add('              whileInView={{ opacity: 1 }}');
add('              transition={{ duration: 1, delay: 0.6 }}');
add('            >');
add('              A comprehensive technical ecosystem spanning from');
add('              <motion.span className="inline-block text-cyber-blue font-medium mx-2" whileHover={{ scale: 1.1 }} transition={{ duration: 0.3 }}>');
add('                cybersecurity');
add('              </motion.span>');
add('              to');
add('              <motion.span className="inline-block text-cyber-purple font-medium mx-2" whileHover={{ scale: 1.1 }} transition={{ duration: 0.3 }}>');
add('                AI/ML');
add('              </motion.span>');
add('              , built with precision and passion.');
add('            </motion.p>');
add('          </motion.div>');
add('          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">');
add('            {skillsCategories.map((category, index) => (');
add('              <SkillCategoryModule key={category.title} category={category} index={index} />');
add('            ))}');
add('          </div>');
add('          <motion.div');
add('            initial={{ opacity: 0, y: 30 }}');
add('            whileInView={{ opacity: 1, y: 0 }}');
add('            transition={{ duration: 1, delay: 1.5 }}');
add('            className="text-center"');
add('          >');
add('            <ScrollReveal direction="up" delay={1.6}>');
add('              <div className="inline-flex items-center space-x-4 px-6 py-3 rounded-full border border-border/20 bg-background/60 backdrop-blur-md">');
add('                <span className="text-sm text-muted-foreground">');
add('                  {skillsCategories.reduce((total, cat) => total + cat.skills.length, 0)}+ Technologies');
add('                </span>');
add('                <span className="text-cyber-blue">&bull;</span>');
add('                <span className="text-sm text-muted-foreground">');
add('                  {skillsCategories.length} Expertise Areas');
add('                </span>');
add('              </div>');
add('            </ScrollReveal>');
add('          </motion.div>');
add('        </div>');
add('      </Container>');
add('    </SectionWrapper>');
add('  )');
add('})');
add('SkillsSection.displayName = "SkillsSection"');
add('');
add('export { SkillsSection }');

fs.writeFileSync("src/sections/skills-section.tsx", lines.join("\\n"));
console.log("Done, lines:", lines.length);
